repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.194'
    hooks:
      - id: ruff
        # Respect `exclude` and `extend-exclude` settings.
        args: ["--force-exclude"]

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: '2.6.2'
    hooks:
      - id: editorconfig-checker
        alias: ec
