repos:
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: '2.6.2'
    hooks:
      - id: editorconfig-checker
        alias: ec

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.194'
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: https://github.com/psf/black
    rev: "22.12.0"
    hooks:
      - id: black
        language_version: python3.11

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.991'
    hooks:
      - id: mypy
