[tool.poetry]
name = "python-lambda-playground"
version = "0.1.0"
description = ""
authors = ["knakayama <knakayama.sh@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
mypy = "^0.991"
aws-lambda-powertools = "^2.5.0"
aws-lambda-typing = "^2.16.3"

[tool.poetry.group.dev.dependencies]
pre-commit = "^2.21.0"
ruff = "^0.0.194"
black = "^22.12.0"
poethepoet = "^0.16.5"
editorconfig-checker = "^2.6.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
strict = true

[tool.poe.tasks]

  [tool.poe.tasks.lint-ec]
  cmd = "ec ."

  [tool.poe.tasks.lint-ruff]
  cmd  = "ruff ."

  [tool.poe.tasks.lint-black]
  cmd = "black ."

  [tool.poe.tasks.lint-mypy]
  cmd = "mypy src"

  [tool.poe.tasks.lint]
  sequence  = [
    "lint-ec",
    "lint-ruff",
    "lint-black",
    "lint-mypy"
  ]
