name: lint

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    env:
      CI: 'true'
    steps:
      - uses: actions/checkout@v3
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: '18.12.1'
          cache: yarn
      - run: yarn install --immutable
      - run: yarn lint
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9.16'
          cache: poetry
      - run: yarn build:app
      - run: yarn build:layer
      - run: yarn lint:app
